linters:
  auto-fix: false
  enable:
    - errcheck
    - goimports
    - revive
    - gosec
    - misspell
    - exportloopref
    - unconvert
    - nakedret
    - gocyclo
    - dupl
    - goconst
    - lll
  disable:
    - structcheck
linters-settings:
  errcheck:
    check-type-assertions: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
  goimports:
    # Choose your own project owner for <codementor>
    local-prefixes: github.com/hedrickbt/go-labs